// Copyright 2026 Jason Holt and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type connection struct {
	Cs  string          `json:"cs"`
	Eva int             `json:"eva"`
	Id  string          `json:"id"`
	Ref json.RawMessage `json:"ref"`
	S   json.RawMessage `json:"s"`
	Ts  string          `json:"ts"`
}

type distributorMessage struct {
	Int string `json:"int"`
	N   string `json:"n"`
	T   string `json:"t"`
	Ts  string `json:"ts"`
}

type event struct {
	Cde   string          `json:"cde"`
	Clt   string          `json:"clt"`
	Cp    string          `json:"cp"`
	Cpth  string          `json:"cpth"`
	Cs    json.RawMessage `json:"cs"`
	Ct    string          `json:"ct"`
	Dc    int             `json:"dc"`
	Hi    int             `json:"hi"`
	L     string          `json:"l"`
	M     json.RawMessage `json:"m"`
	Pde   string          `json:"pde"`
	Pp    string          `json:"pp"`
	Ppth  string          `json:"ppth"`
	Ps    json.RawMessage `json:"ps"`
	Pt    string          `json:"pt"`
	Tra   string          `json:"tra"`
	Wings string          `json:"wings"`
}

type eventStatus struct {
}

type historicDelay struct {
	Ar  string `json:"ar"`
	Cod string `json:"cod"`
	Dp  string `json:"dp"`
	Src string `json:"src"`
	Ts  string `json:"ts"`
}

type historicPlatformChange struct {
	Ar  string `json:"ar"`
	Cot string `json:"cot"`
	Dp  string `json:"dp"`
	Ts  string `json:"ts"`
}

type message struct {
	C    int             `json:"c"`
	Cat  string          `json:"cat"`
	Del  int             `json:"del"`
	Dm   json.RawMessage `json:"dm"`
	Ec   string          `json:"ec"`
	Elnk string          `json:"elnk"`
	Ext  string          `json:"ext"`
	From string          `json:"from"`
	Id   string          `json:"id"`
	Int  string          `json:"int"`
	O    string          `json:"o"`
	Pr   string          `json:"pr"`
	T    string          `json:"t"`
	Tl   json.RawMessage `json:"tl"`
	To   string          `json:"to"`
	Ts   string          `json:"ts"`
}

type multipleStationData struct {
	Station json.RawMessage `json:"station"`
}

type referenceTrip struct {
	C   bool            `json:"c"`
	Ea  json.RawMessage `json:"ea"`
	Id  string          `json:"id"`
	Rtl json.RawMessage `json:"rtl"`
	Sd  json.RawMessage `json:"sd"`
}

type referenceTripLabel struct {
	C string `json:"c"`
	N string `json:"n"`
}

type referenceTripRelation struct {
	Rt  json.RawMessage `json:"rt"`
	Rts string          `json:"rts"`
}

type referenceTripStopLabel struct {
	Eva int    `json:"eva"`
	I   int    `json:"i"`
	N   string `json:"n"`
	Pt  string `json:"pt"`
}

type stationData struct {
	Ds100 string `json:"ds100"`
	Eva   int    `json:"eva"`
	Meta  string `json:"meta"`
	Name  string `json:"name"`
	P     string `json:"p"`
}

type timetable struct {
	Eva     int             `json:"eva"`
	M       json.RawMessage `json:"m"`
	S       json.RawMessage `json:"s"`
	Station string          `json:"station"`
}

type timetableStop struct {
	Ar   json.RawMessage `json:"ar"`
	Conn json.RawMessage `json:"conn"`
	Dp   json.RawMessage `json:"dp"`
	Eva  int             `json:"eva"`
	Hd   json.RawMessage `json:"hd"`
	Hpc  json.RawMessage `json:"hpc"`
	Id   string          `json:"id"`
	M    json.RawMessage `json:"m"`
	Ref  json.RawMessage `json:"ref"`
	Rtr  json.RawMessage `json:"rtr"`
	Tl   json.RawMessage `json:"tl"`
}

type tripLabel struct {
	C string `json:"c"`
	F string `json:"f"`
	N string `json:"n"`
	O string `json:"o"`
	T string `json:"t"`
}

type tripReference struct {
	Rt json.RawMessage `json:"rt"`
	Tl json.RawMessage `json:"tl"`
}
